### ISSUE TITLE
GUI optimizations

### ISSUE THREAD

**Issue by AzraelDD** [fholger/RocksmithToTab#21]
The output path for the gp5 files in the GUI always resets when I reopen the program. It would be more comfortable to have it remember my output path (or all the choices for that matter).
This way I only need to hit create tabs when I got new CLDC.

Also: A tickbox labled "convert official Rocksmith songs" would be neat. This would save some conversion time when I got new CDLC (and make users aware of this feature in the first place).

Those are really minor points, but noteworthy :-)

**Comment by fholger** [comment]
It took a long time, but I finally updated the GUI. It now remembers settings and also stores a simple timestamp in the output directory. If requested, only those psarcs which are newer than that timestamp will be converted on the next run.
Features will be available with the next release.
