### ISSUE TITLE
Settings not being saved / no chords

### ISSUE THREAD

**Issue by johnr2000** [fholger/RocksmithToTab#27]
Hi, good job, great product!

1.  The setting for the Rocksmith 2014 directory that I entered isn't being saved.  It does save the output directory.

Can you make sure that all the settings are saved.  I know the Rocksmith 2014 directory isn't being saved but I didn't test the output type.  If that's not being saved then please save that one too.

2.  I don't see any chords listed in the output.  Should the chords show up like you'd normally see on a tab (above the measures)?

Thanks,

-- John...

**Comment by fholger** [comment]
I know it's taken me forever, but saving of settings is now implemented and will be available in the next release.
