### ISSUE TITLE
SourceForge as a Download Location

### ISSUE THREAD

**Issue by cashewguy** [fholger/RocksmithToTab#29]
This is not strictly an issue with RTT, but more in its availability. SourceForge is a really [going down hill](https://www.google.com/search?q=Source+forge&oq=Source+forge&aqs=chrome..69i57j69i60j69i65l3j69i60.1333j0j7&sourceid=chrome&es_sm=91&ie=UTF-8#q=Source+forge&tbm=nws), and is injecting a lot of things you probably don't want in software (probably not your software specifically).

uBlock actually blocks SourceForge, so it might be a good idea to offer downloads elsewhere.

Thanks!

**Comment by fholger** [comment]
As per your request, I have moved the download location for new versions to http://code.fosshub.com/RocksmithToTab/downloads/
