### ISSUE TITLE
no .psarc files in the RS folder?

### ISSUE THREAD

**Issue by pogue717** [fholger/RocksmithToTab#40]
I'm getting a "Rocksmith 2014 path invalid" error.  Everything is in the right place (D:\Steam\steamapps\common\Rocksmith2014\dlc)  It has worked in the past.  All files end in .psarc.   I've tried downloading another copy of Rocksmith to tab.   Any help?

**Comment by fholger** [comment]
Remove the dlc from the folder. It's expecting the actual Rocksmith install path, not the dlc folder :)

**Comment by pogue717** [comment]
thank you!  
And thank you for developing this program.
